stages:
  - build
  - test
  - deploy

variables:
  APP_IMAGE: inventiv-it
  IMAGE_TAG: $CI_PIPELINE_ID

build-job:
  image: maven:3-jdk-8-alpine
  stage: build
  script:
    - mvn clean package -B
  artifacts:
    paths:
      - target/*.jar

test-job:
  image: maven:3-jdk-8-alpine
  stage: test
  script:
    - mvn test
  artifacts:
    paths:
      - target/*.jar

deploy-job:
  stage: deploy
  variables:
    FF_NETWORK_PER_BUILD: "true"
  script:
    - docker build -t $APP_IMAGE:$IMAGE_TAG .
    - docker run --name=$APP_IMAGE --rm --network=host $APP_IMAGE:$IMAGE_TAG &
    - sleep 10  # Wait for the application to start (adjust as needed)
    - docker ps