workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

variables:
  DOCKER_IMAGE: inventiv-it
  IMAGE_TAG: $CI_PIPELINE_ID


stages:
  - build
  - test
  - build_push_docker_image
  - k8s_deploy

build_job:
  image: maven:3-jdk-8-alpine
  stage: build
  script:
    - mvn clean package -B
  artifacts:
    paths:
      - target/*.jar


unit_test-job:
  image: maven:3-jdk-8-alpine
  stage: test
  script:
    - mvn test
  artifacts:
    when: always
    reports:
      junit: target/surefire-reports/TEST-*.xml
    
docker-job:
  stage: build_push_docker_image
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - echo "docker image tag  $IMAGE_TAG"
    - docker build -t $DOCKER_USERNAME/$DOCKER_IMAGE:$IMAGE_TAG .
    - docker push $DOCKER_USERNAME/$DOCKER_IMAGE:$IMAGE_TAG

deploy_gooogle_k8s:
  stage: k8s_deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  before_script: 

    - kubectl config get-contexts
    - kubectl config use-context soulredouane1/spring-app-ci-cd:google-agent
  script:
    - envsubst < deployement.yml | kubectl apply -f -
  
