trigger:
- master

pool:
  name: default
  demands:
    - agent.name -equals ubuntu-agent


variables:
  JAVA_HOME: '/usr/lib/jvm/java-17-openjdk-amd64'
  JAVA_HOME_17_X64: '/usr/lib/jvm/java-17-openjdk-amd64'
  PATH: $(JAVA_HOME)/bin:$(PATH)

steps:
- script: |
    echo "Java version:"
    java -version
  displayName: 'Check Java version'

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    # mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'