trigger:
- master

pool:
  name: default
  demands:
    - agent.name -equals ubuntu-agent

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'AzureStorage'
    azureStorageAccountName: 'java'
    azureContainerName: 'downloads'
    azureCommonVirtualFile: 'jdk-17.0.8_linux-x64_bin.tar.gz'
    jdkDestinationDirectory: '/usr/lib/jvm/java-17-openjdk-amd64'
# - task: Maven@4
#   inputs:
#     mavenPomFile: 'pom.xml'
#     # mavenOptions: '-Xmx3072m'
#     javaHomeOption: 'JDKVersion'
#     jdkVersionOption: '1.17'
#     jdkArchitectureOption: 'x64'
#     publishJUnitResults: true
#     testResultsFiles: '**/surefire-reports/TEST-*.xml'
#     goals: 'package'